### ISSUE TITLE
Library for android

### ISSUE THREAD

**Issue by truongcoino1** [phithu/rn-zalo#1]
Error of me: Error: Không thể đăng nhập Zalo and when i click login button Zalo app show but screen show grant access and don't login zalo?.
Pls fix for me or give me suggestions to fix this

**Comment by gusonyang** [comment]
Have you solved this problem?

**Comment by truongcoino1** [comment]
issue of me: i built release for android library did not login?

Vào Th 2, 4 thg 11, 2019 vào lúc 21:01 Guson <notifications@github.com>
đã viết:

**Comment by webnah** [comment]
trên oa có cần config: Callback Url gì không, clone và chạy android real device vẫn không login, thay appId tạo trong OA cũng không login, toàn redirect ngược

failed dòng này chăng?
    @ReactMethod
    public void login(final Promise promise) {
        ZaloSDK.Instance.unauthenticate();
        final ReactApplicationContext activity = this.mReactContext;
        final String[] Fields = {"id", "birthday", "gender", "picture", "name"};
        **ZaloSDK.Instance.authenticate**(this.mReactContext.getCurrentActivity(), LoginVia.APP_OR_WEB , new OAuthCompleteListener() {

Instance thành công nhưng khi get profile lại fail
ZaloSDK.Instance.getProfile(activity, new ZaloOpenAPICallback() {
không vào trong khi chạy debug android
}

**Comment by phithu** [comment]
@truongcoino1 Please check 2.1.0

**Comment by chellongCoder** [comment]
I didn't get OAuth code on android, ios ok. :(

**Comment by code2080** [comment]
@chellongCoder I fixed with this PR https://github.com/phithu/rn-zalo/pull/11. Check it out.
