### ISSUE TITLE
Lỗi không getProfile được

### ISSUE THREAD

**Issue by anhdo9797** [phithu/rn-zalo#13]
sau khi em chạy `RNZalo.login();` thì nó log thế này. mong anh giúp đỡ

 {"oauthCode": "8ZupBflXbX5s47Xi-u6sO3j8O1AykASPSK4M5hRbunmt3LOHx_-pRMKPRaYQuRq_7n1uCzVStYmsHHGXjgUZB7v2V5dtqfjwFX9n7elRjX54D0aiZQx08XHtH2gqauXuIbGZ8kl_w5Hp3Z1QgkVwDYCwVZ2wjS0i4nzv4yRGsXyOAGLx_8oNA6njNqB_e8D7PZTFBiVSn59TLm5GfAV541etS66klwufO1PoNzZyyqCqU2OEXlxc8HZGyJgE5WS4OwhIU8G2BaKSYUikrmWICKZwYqIcRqL9EE2Q9v1XIm4oxUKPtsav0_e6Bn71dSyJ", "user": {"error": -1013, "error_description": "Invalid Parameter", "error_name": "Invalid Parameter", "error_reason": ""}}

**Comment by phithu** [comment]
1. Thử login với user khác
2. Xem lại config trong project
