### ISSUE TITLE
[iOS] Calling RNZalo.login() cause crashed on react-native@0.61

### ISSUE THREAD

**Issue by luatnd** [phithu/rn-zalo#8]
Hi, 
I installed rn-zalo and used fully auto-linking on react-native@0.61.5
iOS build process was ok 
=> Then navigated to login screen, pressed a button to call`RNZalo.login()` ==> app crahed, this is the debug content:
> [ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance 0x280f234e0
>   *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZOZaloAuthenticator googleClientIdInPlist]: unrecognized selector sent to instance 0x280f234e0'

Do you have another workaround

Update: Reproduction steps:
-------

1. Init new rn project, the react-native version should be 0.61.5:
```
react-native init testZalo
yarn add rn-zalo
pod install --project-directory=ios
react-native run-ios
```
Some more configuration
```
5. Add URL Type Main target setting -> info -> URL types -> click +
identifier = “zalo”, URL Schemes = “zalo-<YOUR_APP_ID>”

6. Open AppDelegate.m
...
#import <ZaloSDK/ZaloSDK.h>
- (BOOL)application:(UIApplication *)application
 didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    ...
    [[ZaloSDK sharedInstance] initializeWithAppId:@"<YOUR_APP_ID>"];
    return YES;
}
...  

- (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url options:(nonnull NSDictionary<NSString *,id> *)options {
  return [[ZDKApplicationDelegate sharedInstance] application:application openURL:url options:options];
}

7. Clear and Run your project
```
Or you can use /rn-zalo/demo project

2. Run `RNZalo.login()` from JS ==> Worked
3. Install react-navigation:
```
yarn add react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
pod install --project-directory=ios
react-native run-ios
```

4. Run `RNZalo.login()` from JS ==> Crashed

**Comment by phithu** [comment]
For React Native 0.6x. DO NOT RUN ```react-native link rn-zalo```
1. Install pod
2. Add ZaloID to ```Main target setting -> info -> URL types``` (Step 5 in README for iOS Config)
3. Modify ```AppDelegate.m```   (Step 6 in README for iOS Config)

**Comment by luatnd** [comment]
I know the auto-linking mechanism so I don't need to run `react-native link`, 
I think the problem might be the use_framework!

Here my Podfile:
```
....
target 'myapp' do
  use_frameworks!   

  # Pods for react
  # ... List of default pod here ...

  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'Permission-LocationWhenInUse', :path => '../node_modules/react-native-permissions/ios/LocationWhenInUse.podspec'

  use_native_modules!
end

#
# Fix: target has transitive dependencies that include statically linked binaries:
#
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
....
```
Could you ensure that RNZalo will work with `use_framework!`?

**Comment by phithu** [comment]
I don't know. My demo still is working. And Podfile in Demo do not use ```use_framework```.

**Comment by luatnd** [comment]
I think that's the problem!
react-native@0.61 has changed too much.
And many projects is requiring use_framework! 
Can you turn it on and give it a try.
I'm testing it on a newly created blank project.

--- Update ----
Sorry the use_framework! is my other issue (about archiving + bitcode issue), I should not tell it here :D

**Comment by phithu** [comment]
React Native version of demo is ```0.61.5```. Please check demo folder

**Comment by luatnd** [comment]
I try on a new project and still get crashed.
The changes is here:
https://github.com/Pushdy/react-native-pushdy-example/commit/fce7ba8eab85f59458edeb1ef78e6918a787258b

Where is ZOZaloAuthenticator, I cannot found it in the SDK?

**Comment by luatnd** [comment]
I figure out that this issue conflict with `react-navigation`
I updated the reproduction step on the 1st comment.

**Comment by luatnd** [comment]
Can you make the demo project run along with `react-navigation` ?

**Comment by TheBlackHacker** [comment]
For anyone who are looking for solution
ZaloSDK is not working with use_framework!, so you must static include it

**Step1: Add this to your Podfile, before `post_install do |installer|`**
```
$static_framework = ['react-native-zalo-kit']

pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
        installer.pod_targets.each do |pod|
          if $static_framework.include?(pod.name)
            def pod.build_type;
            Pod::BuildType.static_library # >= 1.9
          end
        end
    end
end 
```

**B2: Run "cd ios && pod update"**

Worked on React Native 0.68.2.
