### ISSUE TITLE
Archive Error: bitcode bundle could not be generated 

### ISSUE THREAD

**Issue by luatnd** [phithu/rn-zalo#9]
I got the error when archiving the project, got the same error on 3 projects:

Minimal reproduction steps:
- clone this https://github.com/phithu/rn-zalo
- `cd demo/ios`, install node module and pod
- Product > Run ==> App can be installed and run successfully
- Product > Archive ==>  got the error:

```
ld: bitcode bundle could not be generated because '/Users/luatnd/Downloads/rn-zalo-master/demo/ios/Pods/ZaloSDK/ZaloSDK/Frameworks/ZaloSDK.framework/ZaloSDK(Pods-ZaloSDK-dummy.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/luatnd/Downloads/rn-zalo-master/demo/ios/Pods/ZaloSDK/ZaloSDK/Frameworks/ZaloSDK.framework/ZaloSDK' for architecture arm64
```

**Comment by phithu** [comment]
Demo is working very well. Please check your demo code
https://streamable.com/gjc6y

**Comment by luatnd** [comment]
Hey, please read the issue carefully:

> Product > Run ==> App can be installed and run successfully
> Product > Archive ==> got the error:

You cannot archive it.

**Comment by luatnd** [comment]
Could you ensure that you can archive it without bitcode error?
or re-open this issue?

**Comment by ddtien510** [comment]
I have the same issue
